### ISSUE TITLE
非常棒的站点！有一些问题想请教

### ISSUE THREAD

**Issue by inannan423** [chioio/chioio.tech#1]
您好，您的站点很酷！我也想借助 React 搭建一个类似的 Markdowm 博客应用，请问博主是如何解析 Markdown 文件并生成侧边的目录的呢？感谢您的开源！

**Comment by chioio** [comment]
用的Contentlayer，你可以去看看相关文档和我的源码，通过Nextjs SSG渲染。

**Comment by inannan423** [comment]
好的谢谢！
